db:
  driver: mysql
  user: usrnm
  pass: secret
  class_names: [ 'Atelectasis', 'Cardiomegaly',
                 'Consolidation', 'Edema', 'Enlarged Cardiomediastinum', 'Fracture',
                 'Lung Lesion', 'Lung Opacity', 'No Finding', 'Pleural Effusion',
                 'Pleural Other', 'Pneumonia', 'Pneumothorax', 'Support Devices' ]