root_dir: "/Users/ago/PycharmProjects/mml/data/mimic-cxr-preprocessed"

class_names: ['Pneumonia']
trans_resize: 224
view_position: 'PA'


splitting:
  method: 'random'
  train_val_split: 0.6
  test_val_split: 0.5

seed: 42
